name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: TEST I
      id: test-i
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: TEST I
        setup-command: ''
        command: javac LinkedList.java && java LinkedList
        input: |-
          1
          2
          3
          null
          5
        expected-output: |-
          ENTER INTEGERS TO CREATE NODES (ENTER A NON-INTEGER TO EXIT):
          LINKED LIST CREATED
          LINKED LIST BEFORE INSERTING
          1 -> 2 -> 3 -> null
          ENTER THE ELEMENT TO BE INSERTED:
          Element Inserted
          LINKED LIST AFTER INSERTING
          5 -> 1 -> 2 -> 3 -> null
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-I_RESULTS: "${{steps.test-i.outputs.result}}"
      with:
        runners: test-i
